Repository DDD-Community/ios-tooda, pull requests merged in 2021-05, with the labels that each got.

#2 Feature/add resources
  Tooda/Resources/Assets.xcassets/공통/Contents.json
  Tooda/Resources/Assets.xcassets/공통/camera.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/공통/camera.imageset/camera.png
  Tooda/Resources/Assets.xcassets/공통/camera.imageset/camera@2x.png
  Tooda/Resources/Assets.xcassets/공통/camera.imageset/camera@3x.png
  Tooda/Resources/Assets.xcassets/공통/cancel.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/공통/cancel.imageset/black.png
  Tooda/Resources/Assets.xcassets/공통/cancel.imageset/black@2x.png
  Tooda/Resources/Assets.xcassets/공통/cancel.imageset/black@3x.png
  Tooda/Resources/Assets.xcassets/공통/link.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/공통/link.imageset/link.png
  Tooda/Resources/Assets.xcassets/공통/link.imageset/link@2x.png
  Tooda/Resources/Assets.xcassets/공통/link.imageset/link@3x.png
  Tooda/Resources/Assets.xcassets/공통/more.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/공통/more.imageset/more.png
  Tooda/Resources/Assets.xcassets/공통/more.imageset/more@2x.png
  Tooda/Resources/Assets.xcassets/공통/more.imageset/more@3x.png
  Tooda/Resources/Assets.xcassets/공통/search.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/공통/search.imageset/search.png
  Tooda/Resources/Assets.xcassets/공통/search.imageset/search@2x.png
  Tooda/Resources/Assets.xcassets/공통/search.imageset/search@3x.png
  Tooda/Resources/Assets.xcassets/공통/setting.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/공통/setting.imageset/setting.png
  Tooda/Resources/Assets.xcassets/공통/setting.imageset/setting@2x.png
  Tooda/Resources/Assets.xcassets/공통/setting.imageset/setting@3x.png
  Tooda/Resources/Assets.xcassets/공통/user.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/공통/user.imageset/user.png
  Tooda/Resources/Assets.xcassets/공통/user.imageset/user@2x.png
  Tooda/Resources/Assets.xcassets/공통/user.imageset/user@3x.png
  Tooda/Resources/Assets.xcassets/이모지/Contents.json
  Tooda/Resources/Assets.xcassets/이모지/angry.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/이모지/angry.imageset/angry.png
  Tooda/Resources/Assets.xcassets/이모지/angry.imageset/angry@2x.png
  Tooda/Resources/Assets.xcassets/이모지/angry.imageset/angry@3x.png
  Tooda/Resources/Assets.xcassets/이모지/chicken.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/이모지/chicken.imageset/chicken.png
  Tooda/Resources/Assets.xcassets/이모지/chicken.imageset/chicken@2x.png
  Tooda/Resources/Assets.xcassets/이모지/chicken.imageset/chicken@3x.png
  Tooda/Resources/Assets.xcassets/이모지/omg.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/이모지/omg.imageset/omg.png
  Tooda/Resources/Assets.xcassets/이모지/omg.imageset/omg@2x.png
  Tooda/Resources/Assets.xcassets/이모지/omg.imageset/omg@3x.png
  Tooda/Resources/Assets.xcassets/이모지/pencil.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/이모지/pencil.imageset/pencil.png
  Tooda/Resources/Assets.xcassets/이모지/pencil.imageset/pencil@2x.png
  Tooda/Resources/Assets.xcassets/이모지/pencil.imageset/pencil@3x.png
  Tooda/Resources/Assets.xcassets/이모지/sad.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/이모지/sad.imageset/sad.png
  Tooda/Resources/Assets.xcassets/이모지/sad.imageset/sad@2x.png
  Tooda/Resources/Assets.xcassets/이모지/sad.imageset/sad@3x.png
  Tooda/Resources/Assets.xcassets/이모지/thinking.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/이모지/thinking.imageset/thinking.png
  Tooda/Resources/Assets.xcassets/이모지/thinking.imageset/thinking@2x.png
  Tooda/Resources/Assets.xcassets/이모지/thinking.imageset/thinking@3x.png
Labels: chore

#6 Coordinator 추가 및 DI 개선
  Tooda/Resources/AppCoordinator.swift
  Tooda/Resources/Scene.swift
  Tooda/Sources/Base/BaseViewController.swift
  Tooda/Sources/Core/AppInject.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Factories/ColorSectionFactory.swift
  Tooda/Sources/Navigator/HomeNavigator.swift
  Tooda/Sources/Scenes/Home/Cells/ColorItemCell.swift
  Tooda/Sources/Scenes/Home/Cells/ColorItemCellReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/Home/HomeViewReactor.swift
  Tooda/Sources/Scenes/Home/Section/ColorSection.swift
  Tooda/Sources/Scenes/HomeReactor.swift
  Tooda/Sources/Scenes/HomeViewController.swift
Labels: feature

#5 add Diary Entities
  Tooda/Sources/Entities/Diary/Diary.swift
  Tooda/Sources/Entities/Diary/DiaryImage.swift
  Tooda/Sources/Entities/Diary/DiaryLink.swift
  Tooda/Sources/Entities/Diary/DiaryStock.swift
  Tooda/Sources/Entities/Stock.swift
Labels: feature

#4 add ColorSets
  Tooda/Resources/Colors.xcassets/Contents.json
  Tooda/Resources/Colors.xcassets/backgroundWithAlpha40.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/gray1.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/gray2.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/gray3.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/gray4.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/mainGreen.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/subBlue.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/subRed.colorset/Contents.json
  Tooda/Resources/Colors.xcassets/white.colorset/Contents.json
Labels: chore

#9 Coordinator 개선 및 AppFactory 추가
  Tooda/Resources/AppCoordinator.swift
  Tooda/Sources/Base/BaseViewController.swift
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/AppInject.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Scenes/HomeReactor.swift
  Tooda/Sources/Scenes/HomeViewController.swift
Labels: feature

#8 Feature/API 추가
  Tooda/Sources/Common/ColorLists.swift
  Tooda/Sources/Common/Dictionary+Concat.swift
  Tooda/Sources/Core/Scene.swift
  Tooda/Sources/Entities/Color.swift
  Tooda/Sources/Entities/Note/Note.swift
  Tooda/Sources/Entities/Note/NoteImage.swift
  Tooda/Sources/Entities/Note/NoteLink.swift
  Tooda/Sources/Entities/Note/NoteStock.swift
  Tooda/Sources/Networking/API/AuthAPI.swift
  Tooda/Sources/Networking/API/BaseAPI.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Networking/ColorAPI.swift
  Tooda/Sources/Repositories/ColorRepository.swift
  Tooda/Sources/Test/TestViewController.swift
  Tooda/Sources/UseCases/ColorUseCase.swift
Labels: feature

#7 Feature/다이어리 등록 화면 UI 틀 추가
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryContentCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryImageCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryLinkCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryStockCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/EmptyDiaryLinkCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/EmptyDiaryStockCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryContentCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryImageCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryStockCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/EmptyDiaryLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/EmptyDiaryStockCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/CreateDiaryViewController.swift
  Tooda/Sources/Scenes/CreateDiary/CreateDiaryViewReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Section/DiarySection.swift
Labels: feature

#11 AppAppearance 추가
  Tooda/Resources/Assets.xcassets/back.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/back.imageset/back.pdf
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Core/AppAppearance.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Scenes/HomeViewController.swift
Labels: feature

#10 Feature/Diary 관련 클래스 이름 변경, CustomTextField 추가
  Tooda/Sources/Base/BaseTableHeaderView.swift
  Tooda/Sources/Base/BaseTableViewCell.swift
  Tooda/Sources/Common/BolderTextField.swift
  Tooda/Sources/Common/CommonFunc.swift
  Tooda/Sources/Common/Dictionary+Concat.swift
  Tooda/Sources/Common/JSONDecoder+Optional.swift
  Tooda/Sources/Common/UIColor+Extension.swift
  Tooda/Sources/Common/UIColor+Hex.swift
  Tooda/Sources/Common/UITextField+Extension.swift
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Core/Scene.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Networking/API/AuthAPI.swift
  Tooda/Sources/Networking/API/BaseAPI.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Networking/AccessTokenPlugin.swift
  Tooda/Sources/Networking/Logger.swift
  Tooda/Sources/Networking/NetwokringProtocol.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryContentCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryImageCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryLinkCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/DiaryStockCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/EmptyDiaryLinkCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/EmptyDiaryStockCell.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryContentCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryImageCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/DiaryStockCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/EmptyDiaryLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Cells/Reactors/EmptyDiaryStockCellReactor.swift
  Tooda/Sources/Scenes/CreateDiary/CreateDiaryViewController.swift
  Tooda/Sources/Scenes/CreateDiary/CreateDiaryViewReactor.swift
  Tooda/Sources/Scenes/CreateDiary/Section/DiarySection.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyDiaryLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyDiaryStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteContentCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift
Labels: chore, feature

#14 Feature/네트워킹 로깅 3rd party 라이브러리 추가
  Podfile
  Tooda/Sources/Common/Extensions/AppDelegate+Extension.swift
  Tooda/Sources/Core/AppDelegate.swift
Labels: feature

#15 TextStyle 추가
  Tooda/Sources/Common/UI/TextStyle.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Scenes/HomeViewController.swift
Labels: feature
