Repository DDD-Community/ios-tooda, pull requests merged in 2021-11, with the labels that each got.

#64 [UI] datePicker에서 date를 픽하면 원하는 노트북으로 이동합니다.
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature

#65 [UI] NoteListCell UI를 구현했어요
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Labels: Feature

#66 [UI] 새로운 검색화면을 볼 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/Search/SearchReactor.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature

#68 [UI] 노트 리스트 ViewController의 UI를 구현했어요.
  Tooda/Sources/Common/MarginLabel.swift
  Tooda/Sources/Entities/Note/NoteListModel.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
  Tooda/Sources/SupportFiles/Info.plist
Labels: Feature

#67 [Domain] 주식 종목 입력하기 화면에 대한 Coordinator를 적용했어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#69 [UI] imageCountLabel을 MarginLabel로 수정했어요
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Labels: Feature

#71 [Utils] Info.plist 번들 id 참조 값 변경
  Tooda/Sources/SupportFiles/Info.plist
Labels: Chore

#70 [UI] 종목 기록하기 화면에 TextField를 추가하고 이벤트를 일부 구현했어요.
  Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Labels: Feature

#73 [UI] 노트리스트 화면을 볼 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Labels: Feature

#72 [Bug] 네비게이션바 백버튼을 하면 current 히스토리가 안 남는 문제를 수정합니다.
  Tooda/Sources/Base/BaseViewController.swift
  Tooda/Sources/Common/Extensions/UIBarButtonItem+Extension.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/Search/SearchReactor.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Bug

#74 [UI] 종목 기록하기 화면의 입력 기능을 구현했어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Networking/API/SotckAPI.swift
  Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Labels: Feature

#75 [Domain] 종목 검색 결과 API Response로 Section을 만들어줘요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
  Tooda/Sources/Scenes/AddStock/Cells/StockItemCellReactor.swift
  Tooda/Sources/Scenes/AddStock/Section/AddStockSectionFactory.swift
Labels: Feature, Dependent

#77 [UI] 홈 화면 버튼에 Settings 화면을 연결했어요
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature

#78 [UI] 종목 검색 결과 아이템의 UI를 구현했어요.
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
  Tooda/Sources/Scenes/AddStock/Cells/StockItemCell.swift
  Tooda/Sources/Scenes/AddStock/Cells/StockItemCellReactor.swift
Labels: Feature

#76 [UI] 검색화면에 검색바 UI를 구성합니다.
  Tooda/Sources/Common/UI/TextStyle.swift
  Tooda/Sources/Common/UIColor+Extension.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature, Dependent

#80 [Bug] Base뷰컨 import 문제 수정
  Tooda/Sources/Base/BaseViewController.swift
Labels: Bug

#79 [UI] 종목 검색하기 화면에서 다음 버튼을 추가하고 키보드 영역에 붙여요.
  Tooda/Sources/Common/Keyboard+LayoutGuide.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Labels: Feature

#81 [UI] 검색화면에 빈 최근 검색어 화면을 볼 수 있어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature

#83 [UI] 노트 리스트에서 서버에서 온 노트 리스트를 볼 수 있어요
  Tooda/Sources/Entities/Note/Note.swift
  Tooda/Sources/Entities/Note/NoteLink.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#82 [UI] 종목 기록하기 검색 결과 셀을 터치하면 다음버튼이 활성화 되어요.
  Tooda/Sources/Common/UIColor+Extension.swift
  Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Labels: Dependent

#84 [UI] 검색화면에서 최근 검색어를 볼 수 있습니다. (UI만)
  Tooda/Resources/Assets.xcassets/icon/icon_cancel_black.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/icon/icon_cancel_black.imageset/icon_cancle_black.pdf
  Tooda/Resources/Assets.xcassets/icon/icon_history_14.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/icon/icon_history_14.imageset/icon_history_14.pdf
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Common/UI/TextStyle.swift
  Tooda/Sources/Entities/Search/SearchRecentKeyword.swift
  Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentKeywordCell.swift
  Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentSectionModel.swift
  Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentTitleCell.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature

#85 [Util] 종목 변동률 열거형에 Extension 변수를 정의했어요.
  Tooda/Sources/Entities/Note/NoteStock.swift
Labels: Feature

#88 [UI] NoteListCell에서 '더보기', NoteListViewController에서 더보기, 검색버튼을 볼 수 있어요
  Tooda/Sources/Common/Extensions/UIApplication+Extension.swift
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Common/Extensions/UILabel+Extension.swift
  Tooda/Sources/Common/UIColor+Extension.swift
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature
