Repository DDD-Community/ios-tooda, pull requests merged in 2021-07, with the labels that each got.

#16 Coordinator AppCoordinator 개선
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Labels: Bug

#17 AppColor 추가
  Tooda/Sources/Common/UIColor+Extension.swift
Labels: Feature

#19 UI-UIEdgeInsets init extension 추가
  Tooda/Sources/Common/Extensions/UIEdgeInsets+Extension.swift
Labels: Feature

#20 UIColor Extension 추가
  Tooda/Sources/Common/UIColor+Extension.swift
Labels: Chore, Feature

#21 UI-Sting관련 기능 추가
  Tooda/Sources/Common/Extensions/NSAttributedString+Extension.swift
  Tooda/Sources/Common/UI/TextStyle.swift
Labels: Feature

#22 노트작성 화면 종목 Cell 추가
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift
Labels: Feature, In Progress

#23 [UI] splash 화면 수정
  Tooda/Resources/Base.lproj/LaunchScreen.storyboard
Labels: Update

#26 [UI] 레이아웃 작성 편의를 위한 extension 추가 ( addSubviews )
  Tooda/Sources/Common/Extensions/UIView+Extension.swift
Labels: Improvement

#24 [Core] CommonFunc 일부 추가 및 수정
  Tooda/Sources/Common/CommonFunc.swift
Labels: Improvement

#25 [Core] 로그인 토큰 저장을 위한 KeyChainService 및 LocalPersistanceManager 추가
  Tooda/Sources/Core/AppInject.swift
  Tooda/Sources/Utils/KeyChainService.swift
  Tooda/Sources/Utils/LocalPersistanceManager.swift
  Tooda/Sources/Utils/UserDefaultsService.swift
Labels: Feature

#28 [Util] Date+Extension 추가
  Tooda/Sources/Common/Extensions/Date+Extension.swift
Labels: Chore

#30 [UI] NSAttributedString Extension 추가
  Tooda/Sources/Common/Extensions/NSAttributedString+Extension.swift
Labels: Technical

#29 [Entity] 노트 관련 Entities 변경
  Tooda/Sources/Entities/Note/Note.swift
  Tooda/Sources/Entities/Note/NoteLink.swift
  Tooda/Sources/Entities/Note/NoteStock.swift
Labels: Feature

#27 [Util] AuthorizationService 추가
  Tooda/Sources/Common/RxAuthorization.swift
  Tooda/Sources/Core/AppInject.swift
  Tooda/Sources/SupportFiles/Info.plist
Labels: Chore, Feature
