Repository DDD-Community/ios-tooda, pull requests merged in 2021-09, with the labels that each got.

#37 [UI] 노트 등록 화면에서 이미지 셀을 추가했어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Entities/Note/NoteImage.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteImageItemCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageItemCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/CreateNote/Section/NoteImageSection.swift
Labels: Feature, In Progress

#34 [UI] 로그인 화면 및 로직 구현
  Tooda/Resources/Assets.xcassets/Login/Contents.json
  Tooda/Resources/Assets.xcassets/Login/login.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/Login/login.imageset/login.pdf
  Tooda/Resources/Assets.xcassets/Splash/Contents.json
  Tooda/Resources/Assets.xcassets/Splash/splash.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/Splash/splash.imageset/splash.pdf
  Tooda/Resources/Assets.xcassets/Splash/tooda.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/Splash/tooda.imageset/tooda.pdf
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/AppInject.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Networking/API/AuthAPI.swift
  Tooda/Sources/Scenes/Login/LoginReactor.swift
  Tooda/Sources/Scenes/Login/LoginViewController.swift
Labels: Feature

#38 [Domain] 노트 imageCellReactor를 리팩토링했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Improvement

#41 [Network] 노트 API case 추가
  Tooda/Sources/Networking/API/NoteAPI.swift
Labels: Feature

#42 [UI] 설정의 Cell UI를 구성합니다
  Tooda/Resources/Assets.xcassets/설정/Contents.json
  Tooda/Resources/Assets.xcassets/설정/icon_arrow_right_gray.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/설정/icon_arrow_right_gray.imageset/icon_arrow_right_gray.pdf
  Tooda/Resources/Colors.xcassets/gray5.colorset/Contents.json
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Common/UIColor+Extension.swift
  Tooda/Sources/Scenes/Settings/Cells/SettingsHeaderView.swift
  Tooda/Sources/Scenes/Settings/Cells/SettingsInfoCell.swift
  Tooda/Sources/Scenes/Settings/Cells/SettingsInteractiveCell.swift
  Tooda/Sources/Scenes/Settings/Cells/SettingsSectionFooterView.swift
  Tooda/Sources/Scenes/Settings/Cells/SettingsTableFooterView.swift
  Tooda/Sources/Scenes/Settings/SettingsReactor.swift
  Tooda/Sources/Scenes/Settings/SettingsViewController.swift
Labels: Feature

#43 [Util] 안전한 array index 접근을 위한 Extension 추가
  Tooda/Sources/Common/Extensions/Array+Extension.swift
Labels: Improvement

#40 [UI] 노트 등록 이미지 탭 관련 기능을 추가했어요.
  Tooda/Sources/Common/Extensions/UIViewController+Extension.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature, In Progress

#46 [UI] 홈화면의 노트북 CollectionView에 페이징을 구현합니다.
  Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature
