Repository DDD-Community/ios-tooda, pull requests merged in 2021-12, with the labels that each got.

#86 [UI] 종목 변동률 선택 버튼과, 변동률 타입 선택 뷰를 추가했어요.
  Tooda/Sources/Scenes/AddStock/View/RateButton.swift
  Tooda/Sources/Scenes/AddStock/View/RateSelectView.swift
Labels: Feature, Dependent

#87 [Domain] 종목 변동률 입력 화면을 추가하고, 종목 검색 화면에서 다음 버튼을 누르면 변동률 입력 화면으로 이동해요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
  Tooda/Sources/Scenes/AddStock/View/RateButton.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature, Dependent

#89 [Domain] 최근 검색어를 로컬에 저장하고 볼 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentKeywordCell.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
  Tooda/Sources/Utils/UserDefaultsService.swift
Labels: Feature

#91 [Util] CurrentViewController의 NavigationController 여부에 따라 Push 로직을 변경했어요.
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Labels: Feature

#92 [UI] 종목 검색 결과 리스트 아이템 탭 이벤트를 구현했어요.
  Tooda/Sources/Scenes/AddStock/AddStockReactor.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
Labels: Feature

#90 [UI] 변동률 입력 화면의 기능을 구현했어요.
  Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
  Tooda/Sources/Scenes/AddStock/View/RateSelectView.swift
Labels: Feature

#94 [Entity] 종목 변동률 case를 lowercase로 변경했어요.
  Tooda/Sources/Entities/Note/NoteStock.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
  Tooda/Sources/Scenes/AddStock/View/RateSelectView.swift
Labels: Improvement

#97 [UI] 노트 등록 화면에서 종목 아이템을 스와이프하면 수정, 삭제 UI를 볼 수 있어요.
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Labels: Feature

#93 [UI] 이모지 팝업, URL 입력 팝업의 UI를 구현했어요
  Tooda/Resources/Colors.xcassets/subGreen.colorset/Contents.json
  Tooda/Sources/Base/BaseButton.swift
  Tooda/Sources/Base/BasePopUpView.swift
  Tooda/Sources/Common/OptionsPopUpView.swift
  Tooda/Sources/Common/SelfSizingTableView.swift
  Tooda/Sources/Common/TextInputPopUpView.swift
  Tooda/Sources/Common/UIColor+Extension.swift
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/Login/LoginViewController.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/Cells/OneLineReviewOptionCell.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpReactor.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpViewController.swift
  Tooda/Sources/SupportFiles/Info.plist
Labels: Feature

#98 [Domain] 최근 검색어를 삭제할 수 있습니다.
  Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentKeywordCell.swift
  Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentTitleCell.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
Labels: Feature

#100 [UI] 검색화면에서 빈 검색결과 화면을 볼 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature, Dependent

#102 [Domain] 최근 검색어의 짜잘한 비즈니스 로직을 처리합니다.
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature, Dependent

#99 [UI] UIView에 Gradient와 Shadow를 적용할 수 있어요.
  Tooda/Sources/Common/Extensions/UIView+Extension.swift
Labels: Feature

#96 [Core] Fastlane을 통해 testflight 배포가 가능해요 (fastlane match, testflight upload 기본 세팅)
  Gemfile
  Project.swift
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tooda/Sources/SupportFiles/Info.plist
  fastlane/AppInfo.rb
  fastlane/Appfile
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/README.md
  fastlane/metadata/copyright.txt
  fastlane/metadata/en-US/apple_tv_privacy_policy.txt
  fastlane/metadata/en-US/description.txt
  fastlane/metadata/en-US/keywords.txt
  fastlane/metadata/en-US/marketing_url.txt
  fastlane/metadata/en-US/name.txt
  fastlane/metadata/en-US/privacy_url.txt
  fastlane/metadata/en-US/promotional_text.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/en-US/subtitle.txt
  fastlane/metadata/en-US/support_url.txt
  fastlane/metadata/primary_category.txt
  fastlane/metadata/primary_first_sub_category.txt
  fastlane/metadata/primary_second_sub_category.txt
  fastlane/metadata/review_information/demo_password.txt
  fastlane/metadata/review_information/demo_user.txt
  fastlane/metadata/review_information/email_address.txt
  fastlane/metadata/review_information/first_name.txt
  fastlane/metadata/review_information/last_name.txt
  fastlane/metadata/review_information/notes.txt
  fastlane/metadata/review_information/phone_number.txt
  fastlane/metadata/secondary_category.txt
  fastlane/metadata/secondary_first_sub_category.txt
  fastlane/metadata/secondary_second_sub_category.txt
  fastlane/screenshots/README.txt
Labels: Technical

#103 [Util] UIView에 shadow extension 로직을 개선했어요.
  Tooda/Sources/Common/Extensions/UIView+Extension.swift
  Tooda/Sources/Scenes/CreateNote/View/CreateNoteGuideView.swift
Labels: Improvement

#104 [Domain] 홈 화면에서 노트 등록 가이드 뷰가 보이고, 탭하면 노트 등록 화면을 볼 수 있어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature

#105 [Domain] 노트 등록 화면에 닫기버튼이 보이고, 버튼을 누르면 화면을 내릴 수 있어요.
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature, Dependent

#107 [UI] 노트 등록 화면에 링크 화면을 추가했어요, 그 외 기타 기능 추가
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Labels: Feature

#106 [Core] Tooda에 Firebase Analytics와 Firebase Crashlystics를 설정했어요
  Podfile
  Project.swift
  Tooda/Resources/GoogleService-Info.plist
  Tooda/Sources/Core/AppDelegate.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/Login/LoginReactor.swift
Labels: Technical

#108 [UI] 노트 링크 셀의 UI를 구현했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Labels: Feature

#110 [Domain] 검색화면에서 검색 결과를 볼 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Networking/API/SearchAPI.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature

#111 [UI] 최근 검색어 화면에서 inset을 조정합니다.
  Tooda/Sources/Scenes/Search/SearchRecent/Cells/SearchRecentSectionModel.swift
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentViewController.swift
Labels: Bug, Dependent

#112 [Domain] 검색 화면에서 짜잘한 인터렉션을 추가합니다.
  Tooda/Sources/Scenes/Search/SearchRecent/SearchRecentReactor.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Feature, Dependent

#114 [Core] LinkPreview 라이브러리와 구현체를 추가했어요.
  Podfile
  Tooda/Sources/Core/AppInject.swift
  Tooda/Sources/Utils/LinkPreviewService.swift
Labels: Chore, Feature
