Repository DDD-Community/ios-tooda, pull requests merged in 2022-02, with the labels that each got.

#166 [Domain] 노트 상세 화면에서 노트 수정에 대한 콜백을 받지 못하는 문제를 수정했어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
Labels: Bug

#167 [Domain] 노트 입력 화면에서 링크 아이템을 삭제할 수 있어요. 그외 SwipeCellConfiguration 기능을 개선했어요.
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature, Improvement

#164 [Core] 노트에 대한 글로벌 이벤트버스를 추가하고 홈화면에 대응을 합니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/GlobalEventBus/NoteEventBus.swift
  Tooda/Sources/Entities/Note/Note.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
Labels: Feature

#168 [Domain] 종목 기록하기 Cell에 아이템 추가 제한 기능을 추가했어요. 그 외 기타 수정
  Tooda/Sources/Common/UIColor+Extension.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature, Improvement

#169 [UI] SnackBar(or Toast)를 위한 SnackBarManager를 추가했어요
  Tooda/Resources/Assets.xcassets/snackBar/Contents.json
  Tooda/Resources/Assets.xcassets/snackBar/icon_negative_emoji.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/snackBar/icon_negative_emoji.imageset/icon_negative_emoji.pdf
  Tooda/Resources/Assets.xcassets/snackBar/icon_positive_emoji.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/snackBar/icon_positive_emoji.imageset/icon_positive_emoji.pdf
  Tooda/Sources/Common/Extensions/UIApplication+Extension.swift
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Common/Keyboard+LayoutGuide.swift
  Tooda/Sources/Common/SnackBar.swift
  Tooda/Sources/Utils/SnackBarManager.swift
Labels: Feature

#173 [Domain] 검색 결과를 서버에서 받아올 수 있습니다.
  Tooda/Sources/Common/Extensions/Moya+Decoder.swift
  Tooda/Sources/DTO/Note/SearchNoteResponse.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
Labels: Feature

#170 [Utils] DateComponetType Case를 추가했어요.
  Tooda/Sources/Common/Extensions/Date+Extension.swift
Labels: Feature

#172 [Core] 노트 리스트에 이벤트 버스를 연결하고 로딩 인디케이터를 추가했어요
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Entities/Note/NoteRequestDTO.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
  Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#171 [Domain] 노트 등록/수정 화면에 Global Event에 대한 의존성을 추가하고, 등록/수정 이후에 이벤트를 전달해요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
Labels: Feature

#175 [Domain] 노트 상세 화면에서 이미지 아이템을 볼 수 있어요.
  Tooda/Sources/Common/Extensions/UIImage+Extension.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailImageCell.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Labels: Feature

#174 [Domain] 검색결과 화면에 글로벌 이벤트 처리를 할 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
Labels: Feature

#178 [Bug] 텍스트필드의 attributedString관련한 문제를 수정합니다.
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Bug

#179 [UI] 홈화면에서 빈 이번달 노트북을 클릭하면 노트 생성화면으로 이동합니다.
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature

#177 [Domain] 노트 등록/수정 화면에 짜잘한 예외처리를 구현했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift
Labels: Feature, Improvement

#180 [UI] 검색 결과 화면에서 노트상세 화면으로 이동할 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
Labels: Feature

#181 [UI] 홈화면, 노트검색 결과 화면에 indicator를 추가합니다.
  Tooda/Sources/Entities/Notebook/NotebookMeta.swift
  Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
Labels: Feature, Technical

#182 [Domain] 카메라 권한 관련 기능을 추가하고 이미지 추가 액션시트 기능을 변경했어요.
  Tooda/Sources/Common/RxAuthorization.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/SupportFiles/Info.plist
Labels: Bug, Improvement

#184 [Domain] 노트 등록/수정 화면에서 사용하는 숫자를 상수로 변경했어요.
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Improvement

#183 [UI] 이미지 placeHolder 리소스를 추가하고 화면에 적용했어요.
  Tooda/Resources/Assets.xcassets/icon/icon_addImage_placeHolder.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/icon/icon_addImage_placeHolder.imageset/icon_addImage_placeHolder.pdf
  Tooda/Resources/Assets.xcassets/icon/icon_image_placeHolder.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/icon/icon_image_placeHolder.imageset/icon_image_placeHolder.pdf
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Common/ImagePlaceHolderView.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift
Labels: Feature

#185 [UI] 노트 리스트에 search 버튼을 연결하고 노트 리스트 셀에 image count를 표시했습니다!
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#187 [UI] 자체 QA후, 짜잘한 UI들을 수정합니다.
  Tooda/Sources/Entities/Note/NoteStock.swift
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
  Tooda/Sources/Scenes/AddStock/View/RateButton.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
Labels: Improvement

#186 [UI] 로그아웃, 탈퇴 스낵바와 네트워크 에러 스낵바를 적용했어요!
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/GlobalEventBus/SnackBarEventBus.swift
  Tooda/Sources/Entities/Settings/SettingsSectionModel.swift
  Tooda/Sources/Scenes/Login/LoginReactor.swift
  Tooda/Sources/Scenes/Login/LoginViewController.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
  Tooda/Sources/Scenes/Settings/Cells/SettingsInfoCell.swift
  Tooda/Sources/Scenes/Settings/SettingsReactor.swift
  Tooda/Sources/Scenes/Settings/SettingsViewController.swift
Labels: Feature

#188 [UI] 네이게이션바가 투명하게 되는 이슈 수정했어요
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Improvement

#190 [UI] dynamic height에 맞춰 이미지 레이아웃을 업데이트 했어요
  Tooda/Sources/Common/Extensions/UIImageView+Extension.swift
  Tooda/Sources/Common/Extensions/UILabel+Extension.swift
  Tooda/Sources/Entities/Note/NoteImage.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Labels: Feature

#189 [Domain] 노트 입력/수정 화면과 종목 변동률 입력화면의 이슈를 수정했어요.
  Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailImageCell.swift
Labels: Bug, Improvement

#191 [Domain] 노트 상세 화면에서 노트 삭제 기능을 구현했어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
Labels: Feature

#193 [Domain] 각종 QA 이슈를 수정했어요.
  Tooda/Sources/Scenes/AddStock/AddStockViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift
  Tooda/Sources/SupportFiles/Info.plist
Labels: Bug

#194 [Domain] 노트 등록이 완료되면 호출한 화면에서 상세 화면으로 이동해요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
Labels: Bug, Feature

#195 [Bug] 홈화면 짜잘한 버그들을 수정했어요.
  Tooda/Sources/Scenes/Home/DatePicker/JSDatePicker.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
Labels: Bug

#192 [UI] 자체 QA를 통해 발견된 이슈를 수정했어요
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Tooda/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Tooda/Sources/Common/Extensions/NSAttributedString+Extension.swift
  Tooda/Sources/Common/Extensions/UILabel+Extension.swift
  Tooda/Sources/Core/AppAppearance.swift
  Tooda/Sources/Scenes/Home/Cells/NotebookCell.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpViewController.swift
  Tooda/Sources/Scenes/Search/SearchViewController.swift
Labels: Improvement

#196 [Utils] 노트 등록/수정 화면에서 사진이나 앨범을 선택하면 CropView를 사용할 수 있어요.
  Podfile
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Labels: Feature

#197 [UI] 홈화면에서 defaultIndex를 처리할 수 있습니다.
  Tooda/Sources/Scenes/Home/HomeReactor.swift
Labels: Feature

#199 [Domain] 홈화면에서 노트관련 글로벌 state 이벤트를 받으면 리로드합니다.
  Tooda/Sources/Scenes/Home/HomeReactor.swift
Labels: Improvement

#198 [Domain] 노트 등록/수정 화면에서 네트워킹 에러 처리를 위한 스낵바를 추가했어요. 그외 기타 기능 추가
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#200 [Domain] 노트 등록/수정 화면에서 기본 Alert에 title과 message를 볼 수 있어요.
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpReactor.swift
Labels: Bug, Feature

#202 [Utils] 서버로부터 전달받는 DateFormmat 형식을 변경했어요.
  Tooda/Sources/Common/Extensions/Date+Extension.swift
  Tooda/Sources/Common/Extensions/Moya+Decoder.swift
  Tooda/Sources/Common/Extensions/String+Extension.swift
Labels: Bug

#203 [Domain] 나머지 에러 핸들링을 추가합니다.
  Tooda/Sources/Core/GlobalEventBus/SnackBarEventBus.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/Login/LoginReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultReactor.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
  Tooda/Sources/Scenes/Settings/SettingsReactor.swift
  Tooda/Sources/Utils/SnackBarManager.swift
Labels: Feature

#201 [UI] QA 수정사항 및 추가사항을 반영했어요
  Tooda/Sources/Common/Extensions/Date+Extension.swift
  Tooda/Sources/Entities/Sticker.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/Settings/SettingsReactor.swift
Labels: Improvement

#204 [Domain] 투다의 로그인 관련 이슈를 수정하고 등록/수정 화면을 개선했어요.
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/Login/LoginReactor.swift
Labels: Bug, Improvement

#205 [Core] In-memory image Cache를 추가했어요
  Tooda/Sources/Common/Extensions/UIImageView+Extension.swift
  Tooda/Sources/Scenes/Settings/SettingsViewController.swift
Labels: Improvement

#206 [UI] 기기 대응을 위해 레이아웃을 수정했어요
  Tooda/Sources/Scenes/Login/LoginViewController.swift
Labels: Bug
