Repository DDD-Community/ios-tooda, pull requests merged in 2022-01, with the labels that each got.

#116 [Domain] 노트 등록 화면에서 링크 아이템을 볼 수 있어요. 그 외 기타 변경건 1건
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature, Dependent

#115 [Domain] 검색 결과가 없을 때 처리를 합니다.
  Tooda/Resources/Assets.xcassets/emoji/emoji_tooda_gray.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/emoji/emoji_tooda_gray.imageset/emoji_tooda_gray.pdf
  Tooda/Sources/Common/Extensions/NSAttributedString+Extension.swift
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Scenes/Search/SearchResult/Components/SearchResultEmptyView.swift
  Tooda/Sources/Scenes/Search/SearchResult/SearchResultViewController.swift
Labels: Feature

#120 [Util] UITextField와 UITextView에 유용한 기능을 추가했어요.
  Podfile
  Tooda/Sources/Utils/TextInputLimiter.swift
Labels: Feature

#113 [Core] Github action CI 구성을 위한 테스트 코드를 일부 작성했어요
  .github/workflows/test_on_master.yml
  Podfile
  Project.swift
  ToodaTests/Info.plist
  ToodaTests/Mock/MockCoordinator.swift
  ToodaTests/Mock/MockInject.swift
  ToodaTests/Mock/MockNetworking.swift
  ToodaTests/Scenes/Home/HomeReactorTests.swift
Labels: Technical

#109 [Core] Fastlane에 XCConfig 파일을 다루는 플러그인과 기타 lane을 추가했어요.
  .gitignore
  Gemfile
  Tooda/Sources/SupportFiles/Info.plist
  Tooda/Sources/SupportFiles/configuration/Debug.xcconfig
  Tooda/Sources/SupportFiles/configuration/Release.xcconfig
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/README.md
Labels: Technical, Dependent

#119 [UI] 관련 화면에서 한줄평, 링크 팝업을 볼 수 있어요
  Tooda/Sources/Base/BaseButton.swift
  Tooda/Sources/Base/BasePopUpView.swift
  Tooda/Sources/Common/OptionsPopUpView.swift
  Tooda/Sources/Common/TextInputPopUpView.swift
  Tooda/Sources/Common/UITextField+Extension.swift
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Entities/NoteList/EmojiOptionsSectionModel.swift
  Tooda/Sources/Entities/Sticker.swift
  Tooda/Sources/Scenes/Login/LoginViewController.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/Cells/OneLineReviewOptionCell.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpReactor.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpViewController.swift
Labels: Feature

#122 [Util] Info.plist에서 App Build Number가 누락된 부분을 수정했어요.
  Tooda/Sources/SupportFiles/Info.plist
Labels: Chore

#123 [Domain] 노트 등록 화면의 UI를 수정했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift
Labels: Improvement, In Progress

#127 [Entity] 노트 등록을 위한 DTO를 추가했어요.
  Tooda/Sources/Entities/Note/AddNoteDTO.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
Labels: Feature

#121 [UI] 노트 리스트에서 플로팅 버튼과 빈 화면을 볼 수 있어요
  Tooda/Resources/Assets.xcassets/noteList/Contents.json
  Tooda/Resources/Assets.xcassets/noteList/add_new_note_btn.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/noteList/add_new_note_btn.imageset/add_new_note_btn.pdf
  Tooda/Resources/Assets.xcassets/noteList/icon_smile_emoji.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/noteList/icon_smile_emoji.imageset/icon_smile_emoji.png
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#118 [UI] 빈 노트 상세 화면을 추가합니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
Labels: Feature

#124 [UI] 노트 등록 화면에 "등록" 버튼을 볼 수 있어요.
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature, Dependent

#125 [Domain] 노트 등록 화면의 Section 구조에 Diff 로직을 추가하고 기타 버그를 수정했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/EmptyNoteStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteContentCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteLinkCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/CreateNote/Section/NoteSection.swift
Labels: Bug, Feature, Dependent

#126 [Domain] 노트 등록 화면에서 링크 팝업을 통해 링크 아이템을 등록할 수 있어요.
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#128 [Domain] 노트 등록 화면의 각종 이벤트의 네이밍을 변경했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Improvement, Dependent

#130 [Entity/Utils] 노트 관련 Entities를 변경하고 유용한 Extension을 추가했어요.
  Tooda/Sources/Common/Extensions/Array+Extension.swift
  Tooda/Sources/Entities/Note/AddNoteDTO.swift
  Tooda/Sources/Entities/Note/NoteStock.swift
Labels: Feature, Improvement

#131 [Domain] 노트 등록 화면에서 입력한 정보를 등록할 수 있어요.
  Tooda/Sources/Entities/Note/AddNoteDTO.swift
  Tooda/Sources/Entities/Note/NoteStock.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#129 [Domain] 노트 가이드 뷰화면에 표시된 날짜 텍스트를 노트 등록화면에서 볼 수 있어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/View/CreateNoteGuideView.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature

#117 [UI] 홈화면에서 노트리스트 화면을 볼 수 있습니다.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#133 [UI] NoteListCell에서 shadow가 짤리는 이슈를 수정했어요
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Labels: Bug

#136 [Core] 자동 로그인을 구현했어요
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Utils/KeyChainService.swift
  Tooda/Sources/Utils/LocalPersistanceManager.swift
  Tooda/Sources/Utils/UserDefaultsService.swift
Labels: Feature

#137 [Core] plist를 수정하여 light 모드를 강제하도록 했어요
  Tooda/Sources/SupportFiles/Info.plist
Labels: Technical

#138 [UI] 설정 기본 리스트를 수정하고 인앱 브라우저를 추가하여 연결했어요
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Entities/Settings/PlainSettingsInfo.swift
  Tooda/Sources/Entities/Settings/SettingsSectionModel.swift
  Tooda/Sources/Scenes/Settings/SettingsReactor.swift
  Tooda/Sources/Scenes/Settings/SettingsViewController.swift
Labels: Feature

#139 [UI] 노트 리스트 화면에서 RxTableViewSectionedAnimatedDataSource을 사용하도록 수정했어요
  Tooda/Sources/Entities/Note/Note.swift
  Tooda/Sources/Entities/Note/NoteListModel.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Improvement

#135 [UI] 홈 화면에서 보내주는 Payload에 맞춰 라우팅 수정했어요
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#132 [Domain] 노트 등록 화면에서 순환 참조 이슈를 수정했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageItemCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Bug, Dependent

#140 [UI] 노트리스트 화면에서 페이지네이션 로직을 구현했어요
  Tooda/Sources/Entities/Note/Note.swift
  Tooda/Sources/Entities/Note/NoteListDTO.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature, Dependent

#134 [Domain] 노트 등록 화면에서 종목 아이템을 수정하거나 삭제할 수 있어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteStockCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#145 [Network] 노트 상세 API를 추가했어요.
  Tooda/Sources/Networking/API/NoteAPI.swift
Labels: Feature

#144 [UI] 노트 상세페이지와 관련된 셀들의 기본 UI 레이아웃을 구현했어요
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift
Labels: Feature

#141 [Domain] 홈화면에서 서버에서 받은 노트북 리스트를 받습니다.
  Tooda/Sources/Networking/NetwokringProtocol.swift
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature

#147 [UI] 노트 리스트 화면에 노트 생성화면을 연결했어요
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#143 [Domain] 노트 상세 화면에 tableView을 추가하고 DetailSection을 정의했어요.
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift
Labels: Feature

#142 [Domain] 전달된 노트 데이터로 노트 입력 화면을 그려줘요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Entities/Note/AddNoteDTO.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteContentCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/Cells/Reactors/NoteImageCellReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#149 [Domain] 홈화면에서 과거나 미래 노트북을 볼 수 있습니다.
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Feature

#146 [UI] 노트 리스트 셀에서 날짜 정보와 링크 이미지를 보여주도록 수정했어요
  Tooda/Resources/Assets.xcassets/noteList/icon_link_chain.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/noteList/icon_link_chain.imageset/icon_link_chain.pdf
  Tooda/Sources/Common/Extensions/Date+Extension.swift
  Tooda/Sources/Common/Extensions/String+Extension.swift
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Core/SceneDelegate.swift
  Tooda/Sources/Entities/Note/Note.swift
  Tooda/Sources/Scenes/NoteList/Cells/NoteListCell.swift
Labels: Feature

#150 [Bug] 홈화면에서 initialState를 크래시 안 나게 수정합니다.
  Tooda/Sources/Scenes/Home/HomeReactor.swift
  Tooda/Sources/Scenes/Home/HomeViewController.swift
Labels: Bug

#148 [Domain] 노트 등록 DTO의 이름을 변경했어요.
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Entities/Note/NoteRequestDTO.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#151 [Domain] 노트 수정 API를 추가했어요.
  Tooda/Sources/Entities/Note/NoteRequestDTO.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
Labels: Feature

#152 [Domain] 노트 입력 화면에서 수정 버튼을 추가했어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
Labels: Feature

#153 [Core] 기존 Device ID 로그인을 애플 로그인으로 수정했어요
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/AppInject.swift
  Tooda/Sources/Entities/AppToken.swift
  Tooda/Sources/Networking/API/AuthAPI.swift
  Tooda/Sources/Networking/AccessTokenPlugin.swift
  Tooda/Sources/Scenes/Login/LoginReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Utils/SocialLoginService.swift
  Tooda/Tooda.entitlements
Labels: Feature

#154 [UI] 설정화면에 로그아웃과 탈퇴하기를 추가했어요
  Tooda/Sources/Common/Extensions/UIAlertController+Extension.swift
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Entities/Settings/SettingsSectionModel.swift
  Tooda/Sources/Networking/API/AuthAPI.swift
  Tooda/Sources/Scenes/Settings/SettingsReactor.swift
  Tooda/Sources/Scenes/Settings/SettingsViewController.swift
Labels: Feature

#155 [Core] 노트 리스트 화면에 노트 상세 화면을 연결하고 노트 상세 initial data load 로직을 구현했어요
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Networking/API/NoteAPI.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/NoteDetail/Section/NoteDetailSection.swift
  Tooda/Sources/Scenes/NoteList/NoteListReactor.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#156 [UI] 노트 디테일 화면 header 부분 타이틀, 내용, 스티커를 볼 수 있어요
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTextContentCell.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteStickerCell.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Dependent

#159 [Domain] 노트 상세 화면에서 종목과 링크 아이템을 볼 수 있어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/NoteList/NoteListViewController.swift
Labels: Feature

#162 [UI] 노트 입력 화면과 관련 셀의 제약조건을 변경했어요.
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteContentCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteImageCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteLinkCell.swift
  Tooda/Sources/Scenes/CreateNote/Cells/NoteStockCell.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
Labels: Improvement

#158 [UI] 로그인 버튼을 애플 로그인에 맞게 수정했어요
  Tooda/Resources/Assets.xcassets/Login/icon_apple_logo.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/Login/icon_apple_logo.imageset/icon_apple_logo.pdf
  Tooda/Sources/Base/BaseButton.swift
  Tooda/Sources/Base/BasePopUpView.swift
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewController.swift
  Tooda/Sources/Scenes/Login/LoginViewController.swift
Labels: Feature

#160 [Domain] 노트 상세 화면에서 노트를 수정할 수 있어요.
  Tooda/Sources/Core/AppFactory.swift
  Tooda/Sources/Core/Coordinator/Scene.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputReactor.swift
  Tooda/Sources/Scenes/CreateNote/CreateNoteViewReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailReactor.swift
  Tooda/Sources/Scenes/NoteDetail/NoteDetailViewController.swift
  Tooda/Sources/Scenes/OneLineReviewPopUp/PopUpReactor.swift
Labels: Feature, Dependent

#161 [Core] Coordinator의 pop로직을 수정했어요.
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Labels: Bug

#163 [UI] 화면의 기타 UI를 수정했어요.
  Tooda/Resources/Assets.xcassets/icon/icon_cross_symbol.imageset/Contents.json
  Tooda/Resources/Assets.xcassets/icon/icon_cross_symbol.imageset/icon_cross_symbol.pdf
  Tooda/Sources/Common/Extensions/UIImage+Asset.swift
  Tooda/Sources/Scenes/AddStock/StockRateInputViewController.swift
  Tooda/Sources/Scenes/CreateNote/Cells/EmptyNoteStockCell.swift
  Tooda/Sources/Scenes/NoteDetail/Cells/NoteDetailTitleCell.swift
Labels: Feature, Improvement

#165 [Core] 화면이 dismiss 될 때, completion이 두번 호출될 수 있는 문제를 수정했어요.
  Tooda/Sources/Core/Coordinator/AppCoordinator.swift
Labels: Bug
